[default]
profile_name = "Profile"
player_name = "${Profile_Name}.Player"
profile_created = "1979-05-27T15:32:00.000Z"
sound = "true"

[default_inventory]
warrior = [ [ "sword", "shield",], [ "plate armor", "plate helm",],]
mage = [ [ "staff", "wand",], [ "robe", "hood",],]
items = [ "health potion", "antidote", "mana potion",]

[user.profile]
name = "profile1"
player_name = "player1"
class = "warrior"

[user.settings]
sound = "false"
